"""first migrations

Revision ID: 125e9fb69559
Revises: 
Create Date: 2020-08-16 15:46:13.304458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125e9fb69559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=120), nullable=False),
    sa.Column('about', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('num_users', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_name')
    )
    op.create_table('channel__members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('post_content', sa.String(length=40000), nullable=True),
    sa.Column('image_file', sa.String(length=128), nullable=True),
    sa.Column('video_file', sa.String(length=128), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('num_dislikes', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('num_likes', sa.Integer(), nullable=True),
    sa.Column('num_dislikes', sa.Integer(), nullable=True),
    sa.Column('num_replies', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes__dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('like', sa.Boolean(), nullable=False),
    sa.Column('dislike', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all__reply__comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_comment', sa.Integer(), nullable=True),
    sa.Column('all_reply_comment', sa.String(length=1000), nullable=True),
    sa.Column('all_comment_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['all_comment_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['main_comment'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply__to__comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_comment', sa.Integer(), nullable=True),
    sa.Column('comment_replied_to', sa.Integer(), nullable=True),
    sa.Column('reply', sa.String(length=1000), nullable=True),
    sa.Column('reply_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_replied_to'], ['reply__to__comments.id'], ),
    sa.ForeignKeyConstraint(['main_comment'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['reply_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply__to__comments')
    op.drop_table('all__reply__comments')
    op.drop_table('likes__dislikes')
    op.drop_table('comments')
    op.drop_table('post')
    op.drop_table('channel__members')
    op.drop_table('channel')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
