"""added likes and dislikes as well as replies to comments

Revision ID: bd1b2a322502
Revises: fbf7a626d16c
Create Date: 2020-07-06 13:44:56.712763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1b2a322502'
down_revision = 'fbf7a626d16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('num_dislikes', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('num_likes', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('num_replies', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('num_dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'num_dislikes')
    op.drop_column('comments', 'num_replies')
    op.drop_column('comments', 'num_likes')
    op.drop_column('comments', 'num_dislikes')
    # ### end Alembic commands ###
