"""added the reply_to_comments to the database

Revision ID: e8e17cd7000d
Revises: ee84eac3ac66
Create Date: 2020-07-17 20:57:34.487899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e17cd7000d'
down_revision = 'ee84eac3ac66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply__to__comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.String(length=1000), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('reply_user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reply_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply__to__reply__comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_to_reply', sa.String(length=1000), nullable=True),
    sa.Column('reply_reply_user_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['reply__to__comments.id'], ),
    sa.ForeignKeyConstraint(['reply_reply_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply__to__reply__comments')
    op.drop_table('reply__to__comments')
    # ### end Alembic commands ###
