"""added num_comments column to post table

Revision ID: fbf7a626d16c
Revises: f6ecc44300da
Create Date: 2020-07-03 11:13:56.694626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf7a626d16c'
down_revision = 'f6ecc44300da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('num_comments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'num_comments')
    # ### end Alembic commands ###
